@CodolioApi_HostAddress = http://localhost:5004

### Get a Codolio profile by username
GET {{CodolioApi_HostAddress}}/api/Profile/profile/H
Accept: application/json

###

### Get another Codolio profile by username
GET {{CodolioApi_HostAddress}}/api/Profile/profile/harsh
Accept: application/json

###

### Get a Codolio profile by full profile URL
GET {{CodolioApi_HostAddress}}/api/Profile/profile-by-url?url=https%3A%2F%2Fcodolio.com%2Fprofile%2FH
Accept: application/json

###

### Get raw Codolio profile HTML
GET {{CodolioApi_HostAddress}}/api/Profile/raw-html/harsh
Accept: text/html